# Generated by Django 3.2.9 on 2021-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eight_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='event',
            field=models.CharField(blank=True, choices=[('add', 'add'), ('retrieve', 'retrieve'), ('update', 'update'), ('delete', 'delete'), ('login', 'login'), ('logout', 'logout'), ('password_change', 'password_change'), ('password_reset', 'password_reset'), ('profile_change', 'profile_change')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
