# Generated by Django 3.2.9 on 2021-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eight_logger', '0002_auto_20211202_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipients',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
